name: von_note
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.23.0
  firebase_auth: ^3.10.0
  firebase_analytics: ^9.3.6
  cloud_firestore: ^3.4.9
  sqflite: ^2.0.3+1
  path_provider: ^2.0.11
  path: ^1.8.1
  flutter_svg: ^1.1.5
  share_plus: ^6.0.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.20.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/